name: build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.47.3
      - name: Tests
        run: go test